language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-yoreact' ]; then cd .. && eval "mv $currentfolder generator-yoreact" && cd generator-yoreact; fi

